### ISSUE TITLE
Revaluate distinction between heron and bevy_rapier

### ISSUE THREAD

**Issue by jcornaz** [jcornaz/heron#112]
`rapier` and `bevy_rapier` just published some awesome improvements that will make the user-experience of using rapier in a bevy game much nicer.

If theses changes are awesome, they also makes the distinction between `bevy_rapier` and `heron` a bit thinner and blurry than before.

I think there is still room for both projects as they still have slightly different approaches, and it is likely that they are both useful to a different type of user.

Neverthelless, I have to make sure that efforts in the developement of heron are well spent by making sure that:

* The distinction between `heron` and `bevy_rapier` is big enough and clearily communicated (in the readme).
* Future development of heron go in a right direction to keep `heron` being a relevant alternative to `bevy_rapier`.

**Comment by zicklag** [comment]
Thought it'd be useful if I shared my experience here.

In the last few days I've been getting into Rapier, starting with `bevy_rapier2d`  0.9 and then afterwards switching to `heron`. `bevy_rapier2d` is nice because it gives you tons of direct control over rapier, but the API of `heron` is so much easier to think about. You don't need to worry about the transform updates half as much and everything is clean and simple.

I did instantly run into a few limitations in `heron` which I promptly opened PRs for, but that's really not a problem, and as people use `heron` we'll find out how we want to add more feature bindings to rapier. I'll continue to add issues and pull requests for things I try to do with it. ( eg. I'm currently seeing if it will be easy to upgrade to using rapier 0.9 in the backend, because I'm getting a rapier panic that might be fixed in 0.9 ).

Anyway, I definitely think `heron` has a place and purpose, and that's the ease of use and simple components in its API.

**Comment by jcornaz** [comment]
I added the following documentation in the readme:

> [bevy_rapier](https://github.com/dimforge/bevy_rapier) plugin is an excellent option and should definitely be considered.
> 
> Here are some key differences between the two projects:
> 
> * `heron` tries to provide a smaller, simpler API that is easier to use. `bevy_rapier` is more complete and powerful, but a bit more complex.
> * `heron` mostly hides the underlying physics engine, so you don't have to use [rapier](https://rapier.rs) directly nor [nalgebra](https://github.com/dimforge/nalgebra). `bevy_rapier` asks the user to deal directly with `rapier` and `nalgebra`.
> * `heron` is focused on games only. `bevy_rapier` targets all kind of physics simulation applications (incl. games).
> * `bevy_rapier` is actively maintained by [dimforge](https://www.dimforge.com), the developer of `rapier`. `heron` is also active, but cannot evolve as fast as `bevy_rapier` can. 
> 
> 
> `heron` is probably more suited for simple games and game-jams, where the ease of learn/use is especially valuable and where the lack of advanced feature isn't problematic.
> 
> `bevy_rapier` is probably more suited for bigger/complex games and other types of physics simulations, where it may be better to learn/use a more exhaustive/complex API. 


This should give a good idea of the difference of the two projects, so that users, contributors and myself understand the purpose of `heron`.

Nothing is set in stone. I may review/improve this comparison later. And I, of course, also accept suggestions and contributions.

**Comment by zicklag** [comment]
Looks good to me. :+1:
