### ISSUE TITLE
Make CollisionEvent more ergonomic

### ISSUE THREAD

**Issue by Shatur** [jcornaz/heron#207]
Currently to just check for collision we need to do a lot of checks:
https://github.com/jcornaz/heron/blob/ccec485ddd6ac4ac477af7c353667723874ecdde/examples/events.rs#L51-L61
That use additional helper functions:
https://github.com/jcornaz/heron/blob/ccec485ddd6ac4ac477af7c353667723874ecdde/examples/events.rs#L65-L73

Check for collision is a very common case. So I would propose to add some syntactic sugar to `CollisionEvent` itself to quickly filter collisions. Like functions that accepts collision groups and returns two entities that collides on match (with fixed order) or `None` if the specified groups don't match with the event.

**Comment by jcornaz** [comment]
I initially wanted to improve this area via #19, but it didn't work as easily as I thought it would. So we can continue the discussion here.

Yes, I think a sugar looking like this would be nice:

```

```
I think currently I would suggest a very simple yet powerful solution: Automatically insert and update `Collisions` component that would contain the list of colliding entities.

This means that one could react to collision events by observing the change of that  `Collisions` component instead of listening to the collision events. And because it is a component, one can directly use query filters and even access other components.

Example:

```rust
fn deal_damage_when_hit_by_enemy(mut players_hit: Query<(&mut Health, &Collisions), (With<Player>, Changed<Collisions>)>) {
  for (health, _) in players_hit.iter_mut().filter(|(_, c)| c.is_collided())
}
```

**Comment by Shatur** [comment]
> I was also thinking about a very simple yet powerful solution: Automatically insert and update Collisions component that would contain the list of colliding entities.

@jcornaz  This idea is even better! But what `Collisions` will contain? Should it be just a list of entities?

**Comment by jcornaz** [comment]
> This idea is even better! But what Collisions will contain? Should it be just a list of entities?

Yes, that was my idea, just the set of entities it is collided with.

As a matter of fact, it is quite easy to implement such a system in user-code. In case you want to experiment with it to see how good or bad that idea would turn out in practice.

**Comment by Shatur** [comment]
Okay, I will play with this and send you a PR if the idea will be convenient.

**Comment by Shatur** [comment]
I played with this and like this approach. But what I do not like is that I have to filter unconfigured layers. For example, if I have a pickup with `Pickup` group and `Character` mask I still have to filter walls, floor an other objects that have unconfigured collision layers.

**Comment by Shatur** [comment]
I Godot the whole system is much simpler. You just have layers. And all objects located at first level by default.
