### ISSUE TITLE
Extended collision shape support

### ISSUE THREAD

**Issue by faassen** [jcornaz/heron#61]
Currently Heron supports these bodies, based on Rapier shapes:

* Sphere (circle)

* Capsule

* Cuboid (rectangle)

Here's my analysis of what useful other things exist in Rapier. The Heron body names would typically be the names in Rapier but converted to CamelCase. Ideally all shapes supported by at least 2d would have an implementation in the debug renderer as well.

I think the following have relatively straightforward implementations:

* `convex_hull`  creates a hull around the given points. See #59 

* `round_convex_hull` does a convex hull with rounded corners.

* `round_cuboid`: a cuboid with rounded corners.

* `segment`: a line segment shape from one point to another

* `triangle`. I imagine this is a flat triangle in 3d.

These I'm not entirely sure about what they do.

* `polyline`: polyline shape defined by vertex and optional index buffers. Without index buffers it's assumed to describe a line strip.

* `trimesh`: triangle mesh shape defined by vertex and index buffers. See #41

* `convex_decomposition`: creates a compound shape obtained from the decomposition of the given trimesh (in 3d) and polyline (in 2d) into convex parts

* `round_convex_decomposition`: the same, but with rounded corners

* `convex_decomposition_with_params`: control the decomposition using a set of parameters for the VHACD algorithm.

* `round_convex_decomposition_with_params`: control the decomposition using a set of parameters for the VHACD algorithm.

* `heightfield`: a heightfield shape

* `compound`: a compound shape defined by subshapes

Then there are shapes that only exist in either 2d or 3d. The question is what Heron should do with these as it aims to offer a unified API. The simplest would be to have particular `Body` types to be only constructable in 2d or 3d.

Only exist in 2d:

* `convex_polyline` assumes the given points already form a convex polygon, no convex hull is computed automatically. 

* `round_convex_polyline` does a convex polyline with rounded corners.

Only exists in 3d:

* `cylinder`

* `round_cylinder`

* `cone`

* `round_cone`

Not directly implemented in Rapier but would be nice to implement in Heron is a regular polygon shape defined by the amount of sides.

**Comment by jcornaz** [comment]
Thanks @faassen for this overview.

Heron doesn't have to mirror rapieri's shapes one-to-one. Where rapiers focuses on physics simulation, heron focuses on games. So only the shapes that are the most useful for gamedev should be added. And I would like to "wait for the need" rather than eagerly adding as many shapes as possible.

I think that if heron has sphere, cuboid, capsule and convex-hull (#59) as well as the ability to create multiple colliders for a single body (#11) then the most important missing building blocks would be:

* HeightField (#62)
* Cylinder (#63)
* Cone (#64)

For the other shapes, I'd rather wait until the need actually arise. Of course any good PR is still welcome.

About the "rounded" variants, I think I would appreciate to have a `round: Option<...>` field in the shape itself, rather than having another variant. And again, I would wait until the need arise (or someone open a PR ^^) 

About the shapes that exist only in 2d or 3d: I would probably have these variant behind a `#[cfg(feature = ...)` so the variant is available only if the user has activated the appropriate feature. But I might change my mind about that in the future....

**Comment by faassen** [comment]
Agreed with your analysis, although I still don't know what a HeightField does in a physics context. :)

**Comment by jcornaz** [comment]
> HeightField does in a physics context

This is usually how terrain is represented.

**Comment by jcornaz** [comment]
With all recently added shapes and added support for custom collision shapes (#160), I consider this "epic" done.

More shapes may (and will) still be added. One can create a dedicated issue/pr for shapes that are still missing (and needed)
